title: BookBNB - G5
email: imermet@fi.uba.ar
description: >- # this means to ignore newlines until "baseurl:"
        Esta página contiene la documentación del TP del grupo 5 para 7552 - Taller de programación II - 2020C2.

github_username:  7552-2020C2-grupo5

theme: just-the-docs
plugins:
  - jekyll-feed

collections:
  backoffice:
    permalink: "/:collection/:path/"
    output: true
  backend:
    permalink: "/:collection/:path/"
    output: true
  app:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    backoffice:
      name: Backoffice
    backend:
      name: Backend
    app:
      name: App
