title: BookBNB - G5
email: imermet@fi.uba.ar
description: >- # this means to ignore newlines until "baseurl:"
        Esta página contiene la documentación del TP del grupo 5 para 7552 - Taller de programación II - 2020C2.

github_username:  7552-2020C2-grupo5

theme: just-the-docs
plugins:
  - jekyll-feed

aux_links_new_tab: true
heading_anchors: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
color_scheme: dark
search_enabled: true

aux_links:
  "Github": "https://github.com/7552-2020C2-grupo5"
  "BookBNB Universe": "https://github.com/7552-2020C2-grupo5/bookbnb-universe"
